# Exported from Render on 2024-11-30T10:10:40Z
services:
- type: web
  name: Photobooth
  runtime: python
  repo: https://github.com/ItsHarshitAg/Photo-booth-
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: port
    sync: false
  - key: port
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
version: "1"
