services:
  - type: web
    name: flask-app
    env: python
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 8000  # Render automatically sets a PORT environment variable; this is optional
    healthCheckPath: "/"
